### List all messages
@id=97
@host=http://localhost:3000/messages

GET {{host}}


### Create a new message

POST {{host}}
Content-Type: application/json


{
    "content" : "another message"
}


### Get a particular message
GET {{host}}/{{id}}